export const transactionData = [
  {
    id: "#CIQSB-1092",
    date: "2025-07-15",
    user: "Alice Johnson",
    type: "Booking Payment",
    barber: "Alice Johnson",
    amount: 1200,
    status: "Paid",
  },
  {
    id: "#CIQSB-1092",
    date: "2025-07-16",
    user: "Brian Smith",
    type: "Booking Payment",
    barber: "Alice Johnson",
    amount: 300,
    status: "Paid",
  },
  {
    id: "#CIQSB-1003",
    date: "2025-07-17",
    user: "Catherine Lee",
    type: "Booking Payment",
    barber: "Brian Smith",
    amount: 50,
    status: "Inprocess",
  },
  {
    id: "#CIQSB-1004",
    date: "2025-07-18",
    user: "David Wilson",
    type: "Booking Payment",
    barber:"Catherine Lee",
    amount: 1500,
    status: "Paid",
  },
  {
    id: "#CIQSB-1005",
    date: "2025-07-19",
    user: "Emily Brown",
    type: "Booking Payment",
    barber: "Alice Johnson",
    amount: 1200,
    status: "Paid",
  },
  {
    id: "#CIQSB-1006",
    date: "2025-07-20",
    user: "Frank Harris",
    type: "Booking Payment",
    barber:"Emily Brown",
    amount: 300,
    status: "Paid",
  },
  {
    id: "#CIQSB-1007",
    date: "2025-07-21",
    user: "Grace Thompson",
    type: "Booking Payment",
    barber: "Alice Johnson",
    amount: 75,
    status: "Inprocess",
  },
  {
    id: "#CIQSB-1008",
    date: "2025-07-22",
    user: "Henry Miller",
    type: "Booking Payment",
    barber: "Catherine Lee",
    amount: 1200,
    status: "Paid",
  },
  {
    id: "#CIQSB-1009",
    date: "2025-07-23",
    user: "Isabella Clark",
    type: "Booking Payment",
    barber: "Alice Johnson",
    amount: 1500,
    status: "Inprocess",
  },
  {
    id: "#CIQSB-1010",
    date: "2025-07-24",
    user: "Jack Davis",
    type: "Booking Payment",
    barber: "Emily Brown",
    amount: 300,
    status: "Paid",
  },
];
