export const transactionData = [
  {
    transaction_id: "#TRN-1092",
    date: "2025-07-15",
    buyer: "Alice Johnson",
    seller:"Paul Martin",
    amount: 1200,
    method: "PayStack",
    status: "Paid",
  },
  {
    transaction_id: "#TRN-1092",
    date: "2025-07-16",
    buyer: "Brian Smith",
    seller:"Paul Martin",
    method: "PayStack",
    amount: 300,
    status: "Paid",
  },
  {
    transaction_id: "#TRN-1092",
    date: "2025-07-17",
    buyer: "Catherine Lee",
    seller:"Brian Smith",
    amount: 50,
    method: "PayStack",
    status: "Inprocess",
  },
  {
    transaction_id: "#TRN-1092",
    date: "2025-07-18",
    buyer: "David Wilson",
    seller:"Catherine Lee",
    amount: 1500,
    method: "PayStack",
    status: "Paid",
  },
  {
    transaction_id: "#TRN-1092",
    date: "2025-07-19",
    buyer: "Emily Brown",
    seller: "Alice Johnson",
    amount: 1200,
    method: "PayStack",
    status: "Paid",
  },
  {
    transaction_id: "#TRN-1092",
    date: "2025-07-20",
    buyer: "Frank Harris",
    seller:"Emily Brown",
    amount: 300,
    method: "PayStack",
    status: "Paid",
  },
  {
    transaction_id: "#TRN-1092",
    date: "2025-07-21",
    buyer: "Grace Thompson",
    seller: "Alice Johnson",
    amount: 75,
    method: "PayStack",
    status: "Inprocess",
  },
  {
    transaction_id: "#TRN-1092",
    date: "2025-07-22",
    buyer: "Henry Miller",
    seller: "Catherine Lee",
    amount: 1200,
    method: "PayStack",
    status: "Paid",
  },
  {
    transaction_id: "#TRN-1092",
    date: "2025-07-23",
    buyer: "Isabella Clark",
    seller: "Alice Johnson",
    amount: 1500,
    method: "PayStack",
    status: "Inprocess",
  },
  {
    transaction_id: "#TRN-1092",
    date: "2025-07-24",
    buyer: "Jack Davis",
    type: "Booking Payment",
    barber: "Emily Brown",
    amount: 300,
    status: "Paid",
  },
  {
    transaction_id: "#TRN-1092",
    date: "2025-07-24",
    buyer: "Jack Davis",
    type: "Booking Payment",
    barber: "Emily Brown",
    amount: 300,
    status: "Paid",
  },
];
