export const offerData = [
  {
    id: 1,
    offerName: "CIQFEST",
    date: "2025-07-15",
    couponCode: "CIQFEST",
    maxDiscount: "$50",
    discount: "20%",
    usageStats: "48/100 Used",
    description: "Enjoy 20% off on all summer items!",
    status: "active",
    OfferCondition: "Cart Value", 
    cartValue: "$100", 
    selectedDropdownItems: [],
  },
  {
    id: 2,
    offerName: "CIQFEST",
    date: "2021-08-14",
    couponCode: "CIQFEST",
    maxDiscount: "$70",
    discount: "20%",
    usageStats: "48/100 Used",
    description: "Enjoy 20% off on all summer items!",
    status: "inactive",
    OfferCondition: "Product",
    cartValue: "",
    selectedDropdownItems: [
      { value: "Aloe Locking Gel", label: "Aloe Locking Gel" },
    ],

  },
  {
    id: 3,
    offerName: "Winter Wonderland",
    date: "2022-01-29",
    couponCode: "Winter20",
    maxDiscount: "$60",
    discount: "25%",
    usageStats: "49/100 Used",
    description: "Enjoy 20% off on all summer items!",
    status: "used",
     OfferCondition: "Categories",
    cartValue: "",
    selectedDropdownItems: [
      { value: "Beauty", label: "Beauty" },
    ],
  },
  {
    id: 4,
    offerName: "Spring Blossom",
    date: "2023-12-25",
    couponCode: "Spring21",
    maxDiscount: "$80",
    discount: "30%",
    usageStats: "48/100 Used",
    description: "Enjoy 20% off on all summer items!",
    status: "expired",
    OfferCondition: "Cart Value", 
    cartValue: "$100", 
    selectedDropdownItems: [],
  },
  {
    id: 5,
    offerName: "Autumn Harvest",
    date: "2020-06-12",
    couponCode: "Summer21",
    maxDiscount: "$90",
    discount: "34%",
    usageStats: "200/200 Used",
    description: "Enjoy 20% off on all summer items!",
    status: "active",
    OfferCondition: "Product",
    cartValue: "",
    selectedDropdownItems: [
      { value: "Aloe Locking Gel", label: "Aloe Locking Gel" },
    ],
  },
  {
    id: 6,
    offerName: "Festive Cheer",
    date: "2014-09-09",
    couponCode: "Fall20",
    maxDiscount: "$30",
    discount: "40%",
    usageStats: "55/100 Used",
    description: "Enjoy 20% off on all summer items!",
    status: "active",
    OfferCondition: "Categories",
    cartValue: "",
    selectedDropdownItems: [
      { value: "Beauty", label: "Beauty" },
    ],
  },
  {
    id: 7,
    offerName: "Beach Vibes",
    date: "2019-03-01",
    couponCode: "Winter21",
    maxDiscount: "$20",
    discount: "40%",
    usageStats: "48/100 Used",
    description: "Enjoy 20% off on all summer items!",
    status: "active",
    OfferCondition: "Cart Value", 
    cartValue: "$100", 
    selectedDropdownItems: [],
  },
  {
    id: 8,
    offerName: "Cozy Nights",
    date: "2021-07-10",
    couponCode: "Spring22",
    maxDiscount: "$60",
    discount: "50%",
    usageStats: "54/100 Used",
    description: "Enjoy 20% off on all summer items!",
    status: "active",
    OfferCondition: "Categories",
    cartValue: "",
    selectedDropdownItems: [
      { value: "Beauty", label: "Beauty" },
    ],
  },
  {
    id: 9,
    offerName: "Adventure Awaits",
    date: "2022-04-22",
    couponCode: "Summer22",
    maxDiscount: "$60",
    discount: "55%",
    usageStats: "60/100 Used",
    description: "Enjoy 20% off on all summer items!",
    status: "active",
    OfferCondition: "Product",
    cartValue: "",
    selectedDropdownItems: [
      { value: "Aloe Locking Gel", label: "Aloe Locking Gel" },
    ],
  },
];
