export const AdminPortfolioData = [
  {
    color: "bg-primary1",
    head: "Total Buyers",
    total: "2,148",
    upCount: "8.06",
    MainIcon: "/assets/card/customer.svg",
    description: "+800 New Buyers this month",
  },
  {
    color: "bg-secondary1",
    head: "Total Sellers",
    total: "1327",
    upCount: "8.06",
    MainIcon: "/assets/card/scissors.svg",
    description: "+20 New Sellers this month",
  },
  {
    color: "bg-tertiary1",
    head: "Toal Orders",
    total: "10,089",
    countIcon: "8.06%",
    upCount: "8.06",
    MainIcon: "/assets/card/barbershop.svg",
    description: "-402 Orders from last month",
  },
  {
    color: "bg-quaternary1",
    head: "Total Listings",
    total: "4,987",
    upCount: "8.06",
    MainIcon: "/assets/card/booking.svg",
    description: "+20 Orders this month.",
  },
  {
    color: "bg-quinary1",
    head: "Total Revenue",
    total: "$12,783.00",
    upCount: "8.06",
    MainIcon: "/assets/card/revenue.svg",
    description: "-$402 orders from last month.",
  },
];

export const BarberPortfolioData = [
  {
    color: "bg-primary1",
    head: "Total Appointments",
    total: "1189",
    upCount: "12.5",
    MainIcon: "/assets/card/booking.svg",
    description: "Total Appointments booked",
  },
  {
    color: "bg-quinary1",
    head: "Upcoming Appointments",
    total: "89",
    upCount: "2.4",
    MainIcon: "/assets/card/booking.svg",
    description: "Upcoming Appointments this week",
  },
  {
    color: "bg-quaternary1",
    head: "Today's Appointments",
    total: "18",
    upCount: "0.0",
    MainIcon: "/assets/card/booking.svg",
    description: "Appointments scheduled for today",
  },
];

export const BarbershopPortfolioData = [
  {
    color: "bg-primary1",
    head: "Total Bookings",
    total: "189",
    upCount: "5.2",
    MainIcon: "/assets/card/booking.svg",
    description: "Bookings scheduled for today.",
  },
  {
    color: "bg-quinary1",
    head: "Upcoming Bookings",
    total: "89",
    upCount: "3.1",
    MainIcon: "/assets/card/booking.svg",
    description: "Upcoming Bookings for today.",
  },
  {
    color: "bg-secondary1",
    head: "Active Barbers",
    total: "27",
    upCount: "0",
    MainIcon: "/assets/card/scissors.svg",
    description: "Barbers currently active.",
  },
  {
    color: "bg-quaternary1",
    head: "Booking Revenue",
    total: "$45,200",
    upCount: "10.5",
    MainIcon: "/assets/card/revenue.svg",
    description: "+$5000 this month",
  },
];
